apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hsk-label
  template:
    metadata:
      labels:
        app: hsk-label
    spec:
      containers:
      - name: container
        image: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: newsvc
  namespace: webapps
spec:
  selector:
    app: hsk-label
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort
