apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-appp
  template:
    metadata:
      labels:
        app: my-appp
    spec:
      containers:
      - name: my-container
        image: hemant1111/loginwebapp:1
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: my-servicee
spec:
  type: NodePort
  selector:
    app: my-appp
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 3333
