apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginwebappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loginwebapp
  template:
    metadata:
      labels:
        app: loginwebapp
    spec:
      containers:
      - name: loginwebappcontainer
        image: dockerhandson/spring-boot-mongo
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: loginwebappsvc
spec:
  selector:
    app: loginwebapp
  ports:
  - port: 8888
    targetPort: 8080
  type: NodePort
